### ISSUE TITLE
Italian language not available.

### ISSUE THREAD

**Issue by albanobattistella** [xlmnxp/blue-recorder#47] opened 2023-11-23 19:04 UTC
Hi,

I install the last version, but Italian language is not available.
Could you please check this?
Thank you!
Regards,
A.

**Comment by xlmnxp** [comment] 2023-11-23 20:36
Hello @albanobattistella, this ticket is duplicate of #10

we are facing issues with `gettext`
our next update will be to use Fluent instead of `gettext`
#26

**Closed** 2023-11-23 20:36 UTC
